### ISSUE TITLE
GNOME-Software shows License as Proprietary

### ISSUE THREAD

**Issue by Preisschild** [flathub/org.kicad_pcb.KiCad#17]
![Screenshot](https://user-images.githubusercontent.com/11898437/56847878-f5a9ff80-68e1-11e9-9b50-f553e43fad41.png)

**Comment by jmaibaum** [comment]
At least as of version 5.1.4 (current version available on Flathub), GNOME Software shows the correct license (`AGPL-3.0-or-later`).

I guess this issue can be closed.
