### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kicad_pcb.KiCad#2]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by nedrichards** [comment]
There are screenshots in the appdata: https://github.com/flathub/org.kicad_pcb.KiCad/blob/master/0001-Add-AppStream-metadata.patch#L83

I think you're suffering a bug specific to Endless OS.
