### ISSUE TITLE
No build is created for i386 architecture

### ISSUE THREAD

**Issue by olegkapitonov** [flathub/org.kicad_pcb.KiCad#26]
Builds are created only for the x86_64 architecture since commit https://github.com/flathub/org.kicad_pcb.KiCad/commit/956e1479bcfa23574372ef935de79df5aef2eef8.

i386 build is missing.

**Comment by eszlari** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/437

**Comment by jmaibaum** [comment]
Thanks for the link @eszlari. Closing this, since it is not our fault then.
