### ISSUE TITLE
Language PT

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kicad_pcb.KiCad#3]
Language PT does not work

**Comment by nedrichards** [comment]
Is there an upstream pt_BR translation? Or is this a bug in making it work?

**Comment by LeandroStanger** [comment]
@nedrichards I put in Portuguese of Portugal and is still in English
![captura de tela de 2017-12-12 19-22-41](https://user-images.githubusercontent.com/26097419/33909185-e707c3e0-df71-11e7-9974-c1d16ed2be9e.png)

**Comment by lkundrak** [comment]
Works here.

What does ```flatpak info org.kicad_pcb.KiCad.Locale``` print?
