### ISSUE TITLE
maintainership

### ISSUE THREAD

**Issue by eszlari** [flathub/org.kicad_pcb.KiCad#30]
@jmaibaum Since you seems to have put some work into this flatpak, how about asking for maintainership, like https://github.com/flathub/flathub/issues/1494 ?

**Comment by jmaibaum** [comment]
@eszlari , I would be willing to take maintainership, even though there will likely be phases of inactivity from my side from time to time.

I am still awaiting a response from the core packagers and developers if they want to take over (see: https://lists.launchpad.net/kicad-developers/msg43843.html) before I will open an issue on flathub/flathub.

**Comment by jmaibaum** [comment]
I have just opened the issue on https://github.com/flathub/flathub/issues/1527

**Comment by jmaibaum** [comment]
And just got invited by (and I accepted) so I am closing this now.
