### ISSUE TITLE
kicad-packages3D extension?

### ISSUE THREAD

**Issue by eszlari** [flathub/org.kicad_pcb.KiCad#32]
Due to its size, it might make sense to move `kicad-packages3D` into a separate extension.

**Comment by jmaibaum** [comment]
Thanks @eszlari , this is a good idea. Feel free to send a PR if possible.

**Comment by jmaibaum** [comment]
OK, I have read up a little bit on how flatpak extensions work.

Following [TingPing's blog post about flatpak extensions](https://blog.tingping.se/2018/03/18/flatpaking-plugins.html), I see that we will need to create an extension endpoint like `org.kicad_pcb.Kicad.Library` (to be defined in this repo, as `io.github.Hexchat` does with [`io.github.Hexchat.Plugins`](https://github.com/flathub/io.github.Hexchat/blob/e689fef4d6aaba1fcdeab7218860ac0cafcd334b/io.github.Hexchat.json#L21)).

The actual extension `org.kicad_pcb.KiCad.Library.Packages3D` would then have to be added as an extra package (i.e. a new repo in the flathub organization, like [`io.github.Hexchat.Plugins.Perl`](https://github.com/flathub/io.github.Hexchat.Plugin.Perl)). The structure that is implied here would naturally lead to the other library parts also to be managed as extensions similarly.

**Comment by jmaibaum** [comment]
I have started working on this here:

- https://github.com/jmaibaum/org.kicad_pcb.KiCad/tree/packages3d-extension
- ~https://github.com/jmaibaum/flathub/tree/org.kicad_pcb.KiCad.Library.Footprints~
- https://github.com/jmaibaum/flathub/tree/org.kicad_pcb.KiCad.Library.Packages3D
- ~https://github.com/jmaibaum/flathub/tree/org.kicad_pcb.KiCad.Library.Symbols~
- ~https://github.com/jmaibaum/flathub/tree/org.kicad_pcb.KiCad.Library.Templates~

~As noted by the [WIP] tag in all places, it does not work, yet. To be honest, I did not even complete running `flatpak-builder` locally so far. I have only copied the boilerplate and adjusted paths up until now.~

Update:
The extension endpoint is set up in the above branch, and the extensions seem to install into the expected sub paths. At the moment I am trying to find the correct build switch in KiCad's CMAKE definitions to make it look at the extension endpoint.

**Comment by jmaibaum** [comment]
Another update: I have decided to only move out kicad-packages3d in #34 for now, as the other libraries are a little bit too intertwined right now to make them work as a flatpak extension (see the linked issue above).

#34 will most likely have to wait until the PR to add the `org.kicad_pcb.KiCad.Library.Packages3D` extension has been accepted on flathub.

**Comment by jmaibaum** [comment]
PR to add org.kicad_pcb.KiCad.Library.Packages3D extension is here: https://github.com/flathub/flathub/pull/1539.
