### ISSUE TITLE
crash when typing textbox

### ISSUE THREAD

**Issue by HeavyMoon** [flathub/org.kicad_pcb.KiCad#44]
i want to use KiCad on CentOS7.
but KiCad crash when typing textbox.
how can i debug and fix it?
i'm not familiar with flatpak.

this is the error message.
```
The program 'kicad' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadLength (poly request too large or internal Xlib length erro'.
  (Details: serial 844995 error_code 16 request_code 18 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

version of kicad
```
Application: KiCad
Version: 5.1.7, release build
Libraries:
    wxWidgets 3.0.5
    libcurl/7.71.1-DEV GnuTLS/3.6.14 (NSS/3.49.2) (OpenSSL/1.1.1g) zlib/1.2.11 libidn2/2.3.0
Platform: Linux 5.6.6-1.el7.elrepo.x86_64 x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
    Boost: 1.74.0
    OpenCASCADE Technology: 7.4.0
    Curl: 7.71.1-DEV
    Compiler: GCC 10.2.0 with C++ ABI 1014

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=OFF
    KICAD_USE_OCC=ON
    KICAD_SPICE=ON
```

**Comment by jmaibaum** [comment]
Thank you for your report.

To debug, you should install the debug extension first: `flatpak install org.kicad_pcb.KiCad.Debug` in order to get better stack traces.

Then, you can start a shell from inside the sandbox: `flatpak run --command=sh --devel org.kicad_pcb.KiCad`. Start gdb with: `gdb /app/bin/kicad`, and try to reproduce the crash.

More detailed information about debugging flatpak apps can be found in the flatpak wiki: https://docs.flatpak.org/en/latest/debugging.html

Please note that KiCad core developers are likely not reading these tickets, so please make sure to report your findings to the official issue tracker on Gitlab.com: https://gitlab.com/kicad/code/kicad/-/issues

**Comment by HeavyMoon** [comment]
Thank you for your comment.

Kicad v4.0.6 in the epel repository is fine.
This issue only occurs with flatpak.
I know that flatpak is not supported by kicad project.
so I will consider methods other than flatpak...

as a side note,,,
gdb shows 'No debugging symbols found'.
```
$ flatpak list --all | grep -i kicad
org.kicad_pcb.KiCad/x86_64/stable	user,current
org.kicad_pcb.KiCad.Debug/x86_64/stable	user,runtime
org.kicad_pcb.KiCad.Locale/x86_64/stable	user,runtime,partial
$ flatpak run --command=sh --devel org.kicad_pcb.KiCad 
sh-5.0$ gdb /app/bin/kicad
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /app/bin/kicad...
(No debugging symbols found in /app/bin/kicad)
(gdb) 
```

**Comment by jmaibaum** [comment]
I will investigate why there are no debug symbols built and stored into the .Debug extension with the standard build if I find time.

Would you mind sharing a few more details of what steps exactly lead to your crash? I would like to try and reproduce it either in flatpak or using other distro packages.

Into which textbox are you typing what to crash KiCad? Feel free to reopen with more information.

**Comment by HeavyMoon** [comment]
@jmaibaum
Thank you for your comment again.

probably the language setting is related to this issue .
regardless of English characters or Japanese characters that i typed,  this issue occurred.

## how to reproduce
1. Start "KiCad"
2. Select Japanese (Settings> Language Settings> Japanese) and restart
3. Create a new project
4. Launch "Eeschema"
5. Open "Page Settings"
6. Enter something in the text box (anywhere)
  - Input is fine. Sometimes it doesn't work ...
  - Delete and backspace looks not working. but when I click other area except of 'Page Settings', I get the following message and the characters are removed:
```
(kicad:3): GLib-GObject-CRITICAL **: 21:29:53.220: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
  - Keep typing and deleting the appropriate characters. then sometimes crash with the following message:
```
(kicad:3): Gdk-ERROR **: 21:29:58.101: The program 'kicad' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadLength (poly request too large or internal Xlib length erro'.
  (Details: serial 1687513 error_code 16 request_code 18 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Can you reproduce it? need more details?
i built docker container for KiCad,  so If you could not reproduce this, i'll give up to use this flatpak version.

**Comment by jmaibaum** [comment]
Hi @HeavyMoon , thank you for the info.

So far, I am not able to reproduce. I tried switching the screen language to Japanese, but this failed due to missing locale on my machine. I thus tried only English and German for now, but they both seem fine. Entering and deleting any character into Eeschema's page settings works without wrong behaviour or crashes.

Will continue trying to reproduce at the weekend. Did you check the official KiCad bugtracker for simliar issues related to Japanese language and the Eeschema page settings, yet?

Does this issue only happen in Eeschema's page settings? Or does it also happen with the page settings dialogs in other applications like Pcbnew?

**Comment by HeavyMoon** [comment]
Sorry for my late reply

No similar issues related to Japanese were found.
not only Eeschema's page settings. 
similar issues occur at almost all text boxes in applications like Pcbnew, Preferences, etc.
